### PR TITLE
Standalone app

### PR DESCRIPTION
**Pull request by greenflash1986**
Hi,
I tried to bring back the standalone app for NLP and was successful. You could say it's a work in progress. But as I don't know if I got the idea from https://github.com/microg/UnifiedNlp/issues/179#issue-511220677 correct this is a request to help me out / give some ideas / make some points for the roadmap for the standalone app.
Unfortunatly I'm not an experienced Android developer but I'll try my best to learn and spend some time for this project.

Best regards
Samuel

cc: @erfanoabdi
I've already seen you PR but as I understand Issue 179 there should be another structure and the app should use the service together with the client and the different implementations. So I tried to implement the standalone app the way I understand it.

### CODE REVIEW

**Comment by erfanoabdi** [comment]
i'm not sure if i understood correctly but my app is also using new structure, by just calling UnifiedLocationClient service (same as current GMScore)

**Comment by greenflash1986** [comment]
Damn! It!
You're right. This is a little bit embarrassing... :-/ I had seen the code you checked in, compared it with the structure of the old app and came to the conclusion that it's just the old app. I'm very sorry for my assumption :-(

Comparing my PR with your PR I guess yours does have more completed work. I will close my PR. I could also delete the repo in my account. But maybe you are interested in the two tests I've written? (idea behind it is to do some automated tests with images (not) including Gapps.)
Are you interested to assist each other if @mar-v-in  (or other maintainers of UnifiedNLP)  give some hints how to bring the standalone app back to live?

Again: very sorry for my "uncomplete understanding of your work" and my assumption. 
Best regards

**Comment by erfanoabdi** [comment]
no problem mam, thanks for looking at my work.
yeah tests looks nice, i'll give it a try when got some time

Best regards

**Comment by greenflash1986** [comment]
Better idea: i will do the tests on YOUR branch and send a PR for / to you :D will give me some better understanding of your work

**Pull request closed without merging**
